version: 2
project_name: apadana

builds:
  -
    id: "chapar"
    binary: chapar
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    main: cmd/chapar/main.go
    ldflags:
      - -s -w -X main.version={{.Version}}

  -
    id: "spasaka"
    binary: spasaka
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    main: cmd/spasaka/main.go
    ldflags:
      - -s -w -X main.version={{.Version}}

  -
    id: "satrap"
    binary: satrap
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    main: cmd/satrap/main.go
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  -
    formats: ["zip"]
    name_template: "{{ .ProjectName }}-{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}-{{ .Arch }}-checksum.txt"
  split: true

changelog:
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'Merge pull request'
      - 'Merge branch'
